### ISSUE TITLE
Compose and finish the UI of the FE

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#113]
## User story
1. As a user of the building information system,
2. I want a unified user interface that integrates the map view, data view, and main architecture into a single panel,
3. So that I can easily navigate and use the system without having to toggle between different views, enhancing usability and efficiency.

## Acceptance criteria
* The map view, data view, and main architecture should be seamlessly integrated into a single, cohesive user interface panel.
*  Users should be able to interact with the map, access data, and utilize main architecture features from this unified interface without needing to switch contexts.
* The design must be responsive, ensuring that the interface adjusts appropriately across different devices and screen sizes.
* Ensure that all functionalities of the individual components are preserved and function correctly in the integrated UI.
* User interface elements should be consistent in style, interactions, and accessibility, adhering to the established design system.

## Definition of done (DoD)
* Integration of all three frontend components (map view, data view, main architecture) is complete and functional.
* Documentation has been updated to reflect the new UI integration and usage guidelines.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

## Related tickets
* system design: https://github.com/amosproj/amos2024ss04-building-information-enhancer/issues/135
* visualization: https://github.com/amosproj/amos2024ss04-building-information-enhancer/issues/165

**Comment by Lucas-Nan** [comment]
architecture design in https://github.com/amosproj/amos2024ss04-building-information-enhancer/issues/135
