### ISSUE TITLE
Update the CI-CD for the new BE

### ISSUE THREAD

**Issue by Corgam** [amosproj/amos2024ss04-building-information-enhancer#139]
## Description

The CI-CD pipeline should be updated for the new containers from the BE.

## Acceptance criteria
* Working, single docker-compose for the whole project.
* Updated documentation for the pipeline.
* Updated readme in the root folder
* Updated GitHub actions for the CI-CD.

**Comment by Corgam** [comment]
An old version of #257

**Comment by op-hub** [comment]
Duplicate
