### ISSUE TITLE
Padding on FE Search

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#169]
**Describe the bug**
Searching for something in the FE searchbar messes up some padding

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dancingsushii** [comment]
Closed as duplicate of [#168](https://github.com/amosproj/amos2024ss04-building-information-enhancer/issues/168).
