### ISSUE TITLE
Decide on API endpoints - to have one hour meeting

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#17]
## User story
1. As a developer,
2. I want to decide on the API endpoints for our application,
3. So that there is a clear contract between the frontend and backend teams regarding data exchange.

## Acceptance criteria
* Conduct a meeting to discuss frontend and backend requirements and align them with the overall project objectives.
* Define and document the API endpoints that will meet the project's needs, considering data types, security, and efficiency.
* API endpoints should include necessary operations (GET, POST, PUT, DELETE) as relevant to the application’s functionality.

## Definition of done (DoD)
* A meeting has been conducted with frontend and backend teams to discuss and finalize API endpoints.
* API endpoint specifications have been documented and include paths, request/response formats, and expected behaviours.
* API mockups or prototypes have been created for initial testing and feedback.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by dancingsushii** [comment]
Notes: specification from FE team to BE -> decide on endpoints

**Comment by Lucas-Nan** [comment]
minimal version was decided in meeting with bounding lattitude/longitude and map id as input and returning a geojson featurecollection as return

**Comment by dancingsushii** [comment]
Meeting note: https://github.com/amosproj/amos2024ss04-building-information-enhancer/wiki/Meeting-notes-%E2%80%90-Team-meetings#api-endpoints-discussion
