### ISSUE TITLE
Polishing Frontend

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#173]
## User story
1. As a sustainability expert,
2. I want to find needed data,
3. So that the frontend of the application is user-friendly and accessible.

## Acceptance criteria
This is the big epic that consists of some frontend refinement tickets. To bring this to the finished state, the following tickets must be completed:

Bugs:
* #177 
* #178
* #179
* #169 
* #182

Features:
* #180
* #181
* #183
* #184
* #185
* #215
* #238 
* #239

## Definition of done (DoD)
* All tickets are fully functioning, done and well tested.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Corgam** [comment]
Worked on:
- #224 
- #229 
- #230
