### ISSUE TITLE
Map interaction from search

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#183]
## User story
1. As a user,
2. I need to be able to select a location from the search results,
3. So that it can be automatically shown on the map.

## Acceptance criteria
* Selecting a location from the search results immediately focuses the map on the selected location.
* The map zooms in to a predefined level that best displays the selected location.

## Definition of done (DoD)
* User feedback on this feature is consistently positive in usability tests.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Lucas-Nan** [comment]
currently only with default values

**Comment by Lucas-Nan** [comment]
flyto by lucas, actual coords from suggestions is from celine

**Comment by dancingsushii** [comment]
So your part is done, @Lucas-Nan? Now only the rest is on @CelineMP?

**Comment by CelineMP** [comment]
@dancingsushii 
@Lucas-Nan implemented a function that is called when a search result is entered to fly to a coordinate. I expanded on it to also fly to areas within their bounds. So this is done.
This ticket is for displaying the area even better: https://github.com/orgs/amosproj/projects/42/views/1?filterQuery=celine&pane=issue&itemId=64937245

**Comment by dancingsushii** [comment]
Oh, okay, then I am closing this issue.
