### ISSUE TITLE
Discuss Labels and Milestones

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#19]
## Task specs
POs discuss restructering labels and Milestones
Suggestions:
* Add BE / FE / ci/cd label
* Remove milestones

**Comment by op-hub** [comment]
Agreement: Delete milestones for now, maybe add them later

**Comment by dancingsushii** [comment]
To do: discuss it again in Sprint 4 or Sprint 5.

**Comment by dancingsushii** [comment]
Idea: To have two milestones: mid-term and final release.

**Comment by op-hub** [comment]
Milestone: Workpackages based in requirements from IP
Labels: Further discuss in upcoming sprint(s)

**Comment by op-hub** [comment]
POs agreed on: tickets for buisness value features
Link technical tickets in buisness feature tickets
