### ISSUE TITLE
Change map controll button visibility

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#210]
**Describe the bug**
The two map control icons(search and switching) to satellite view are hard to see when zoomed in on some forest region. Additonal the lower button overlaps with the leaflet banner 

**To Reproduce**
1. Go to test environment
2. Click on switch icon
3. Zoom into map

**Expected behavior**
Button is always clearly visible
Buttons dont overlap leaflet banner

**Screenshots**
![Image](https://github.com/amosproj/amos2024ss04-building-information-enhancer/assets/115190775/14e4ffec-04a5-4d0a-8857-484713b24466)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Corgam** [comment]
Finished in the #224
