### ISSUE TITLE
Documentation - BE technology

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#22]
## User story
1. As  a development team,
2. We want comprehensive documentation for our backend technology stack,
3. So that all team members have a clear understanding of our backend systems and can efficiently work with or modify the system.

## Acceptance criteria
* Document the structure of YAML parser.
* Document the structure of CSV parser.
* Document the structure database connection.
* Document the structure of row mapping/filtering.

## Definition of done (DoD)
* Wiki is enriched with all data and information from implementation tasks.

## Note
* Starting from the next sprint documentation task will be automatically included into development scope of each implementation.

**Comment by Superschnizel** [comment]
https://github.com/amosproj/amos2024ss04-building-information-enhancer/wiki/Data-Pipeline
https://github.com/amosproj/amos2024ss04-building-information-enhancer/wiki/Backend-Architecture
