### ISSUE TITLE
Comprehensive map marker enhancements

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#245]
## Description
Enhance the map's functionality and user interaction by upgrading marker aesthetics, making them clickable, and improving the distinguishability of merge-markers. This comprehensive update aims to make the map more intuitive, visually appealing, and informative for users.

## Acceptance criteria
* #279 

## Acceptance criteria
* New marker design with icons embedded in an empty marker enhances visual appeal and usability.
* Markers are interactive; clicking on a marker displays detailed information about the location or dataset.
* ~~Merge-markers are easily distinguishable, clearly indicating their associated datasets.~~

## Tasks
- Design update: Create a unified marker design that incorporates icons within a visually appealing empty marker.
- Clickable functionality: Implement click functionality for each marker, showing a pop-up or sidebar with detailed information when a marker is clicked.
- Integration and Testing: Integrate these features into the existing map system, ensuring compatibility and performance. Conduct thorough testing with users to gather feedback and make necessary adjustments.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Lucas-Nan** [comment]
merge icon functinality is done
