### ISSUE TITLE
Transfer all meeting notes and other relevant documentation to GitHub

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#25]
## Task specs
Transfer all existing meeting notes and relevant project documentation into a single, accessible location on GitHub.

- [ ] Add all the notes to [the main page](https://github.com/amosproj/amos2024ss04-building-information-enhancer/wiki/Meeting-notes-%E2%80%90-Team-meetings)

## Deadline
15.05.2024

## Notes
* Ensure all team members are informed of the new documentation repository location and how to access it.

**Comment by dancingsushii** [comment]
To be done: have plain-text meeting notes.

**Comment by dancingsushii** [comment]
Solved by creating a custom sidebar for having meeting notes in the TOC format.

https://github.com/amosproj/amos2024ss04-building-information-enhancer/assets/46463790/b8668f6a-e7bc-4028-b8d4-026e57f79142
