### ISSUE TITLE
Test environment connection bugs from mid-project review

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#251]
**Describe the bug**
During mid-project review we spotted some bugs, that are presumably happening because of 

- Cited from @Corgam: There is an url to connect to the DB based on which environment the app is in. So locally it will connect to localhost:8081 and for test env to http://test.amos.b-ci.de:8081.
- Cited from @Corgam: when I switched it manually, the connection was blocked by cross-reference CORS (Maybe it is as easy as adding to header  Access-Control-Allow-Origin "*").

**To Reproduce**
1. Go to test environment
2. Click something
3. See not available service

**Expected behavior**
Correctly working test environment.

**Additional context**

**Comment by Corgam** [comment]
Finished with #265 and #266

**Comment by Corgam** [comment]
Finished with commit ce575bcd796f09f82dfdde8ed583954874707c9f
