### ISSUE TITLE
Extend the BE docker architecture and CI/CD pipeline

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#257]
## Description
Enhance the existing backend Docker architecture and CI/CD pipeline to incorporate new components and improve deployment efficiency.

## Acceptance criteria
* New API Gateway has been successfully added and integrated.
* The old API Gateway has been renamed to API Composer without disrupting existing functionalities.
* CI/CD pipeline has been reworked to include and manage new Docker images effectively.
* Code migration from the old API Gateway is planned and executed, if feasible within the sprint constraints.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Corgam** [comment]
Finished with #260
