### ISSUE TITLE
Implement MongoDB metadata DB

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#259]
## Description
Implement and integrate a new MongoDB database container to manage metadata effectively.

## Acceptance criteria
* MongoDB database for metadata is set up in a new container and integrated with the backend.
* Metadata handling is successfully transitioned from the frontend to MongoDB, ensuring data integrity and efficiency.
* MongoDB is connected to relevant API endpoints, allowing for seamless data interactions.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by op-hub** [comment]
Duplicate
