### ISSUE TITLE
Queryable max zoom level for individual datasets

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#271]
**Describe the bug**
Show zoom level label if it is necessary for a dataset

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lucas-Nan** [comment]
this very much depends on the performance but of course it can already be added

**Comment by Corgam** [comment]
Duplicate of [#318](https://github.com/amosproj/amos2024ss04-building-information-enhancer/issues/318)
