### ISSUE TITLE
Utilize metadata DB to store metadata

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#277]
## Description
Implement the use of a metadata database to centralize and streamline access to dataset metadata.

## Acceptance criteria
* Metadata for all relevant datasets is migrated to and managed in the metadata DB.
* The system retrieves metadata from the DB efficiently.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Corgam** [comment]
Finished by #295
