### ISSUE TITLE
Implement an ability to click on the map icon to get info about a specific marker

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#279]
## Description
Develop hover functionality for map icons that allows users to view detailed information about a specific marker without additional clicks.

## Acceptance criteria
* Hovering over a map icon displays detailed information about the marker in a tooltip or a small popup.
* Information display is responsive and does not cause lag or disrupt other map functionalities.
* UI design for the hover information is clear and matches the overall design of the map interface.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Corgam** [comment]
Discussed with @Lucas-Nan that a click would be better than a hover. Agreed by @op-hub
