### ISSUE TITLE
Discussion about: API Composer: merge the viewportData endpoints into a single endpoint, using the datasetID field

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#280]
## Description
Consolidate the existing viewportData endpoints into a single endpoint to streamline API management and improve efficiency, using the `datasetID` field to differentiate data sources.

## Acceptance criteria
* A single API endpoint replaces multiple viewportData endpoints.
* The endpoint correctly handles requests by using `datasetID` to fetch respective data.
* API performance is maintained or improved with the consolidation.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Lucas-Nan** [comment]
discussion was already done for api-gateway. result was not disliked by ahsan on api pr
