### ISSUE TITLE
BE problems when retrieving Hausumringe from database

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#282]
**Describe the bug**
Behavior: Slow responses, crashes

Investigate further: for reproducing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lucas-Nan** [comment]
okay so a limiting factor for testing this stuff is simply that the datapipeline takes somewhere between 2 and 3 hundred years to run through. this request here: "http://localhost:8082/api/v1.0/Dataset/2/clustereddata?ZoomLevel=17&BottomLat=49.278095&BottomLong=10.674285&TopLat=49.28214&TopLong=10.680475" works for clustereddata but not for the data directly

**Comment by Lucas-Nan** [comment]
so http://localhost:8082/api/v1.0/Dataset/2/data?ZoomLevel=17&BottomLat=49.278095&BottomLong=10.674285&TopLat=49.28214&TopLong=10.680475 doesnt work currently. i try to rerun the pipeline since the cluster also didnt return every house footprint
- instead we got this: 

![Image](https://github.com/amosproj/amos2024ss04-building-information-enhancer/assets/166795065/f3a81f24-5d43-4b2a-b02a-01734f757875)

which is nice but not enough

**Comment by Lucas-Nan** [comment]
@Ahsankkhan  so please check this call on your setup / your db and tell me your results

**Comment by Lucas-Nan** [comment]
another thing both of these things return the same with clustereddata request

http://localhost:8081/api/getDatasetViewportData?BottomLat=48.97904736754763&BottomLong=10.38553584149015&TopLat=48.98239910897947&TopLong=10.397916918302892&ZoomLevel=16&datasetID=house_footprints

http://localhost:8081/api/getDatasetViewportData?BottomLat=48.962821334165405&BottomLong=10.249106519661012&TopLat=48.966174166620476&TopLong=10.261487596473755&ZoomLevel=16&datasetID=house_footprints

**Comment by Lucas-Nan** [comment]
bug is a result of bad performance. Improvements to be added here: https://github.com/amosproj/amos2024ss04-building-information-enhancer/wiki/Performance-Considerations-for-FE-and-BE
