### ISSUE TITLE
Improve database indexing logic

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#306]
## Description
Optimize parametrization for index creation, including research about resolution layer (dataset dependent)

## User story
1. As a User
2. I want need the database performance increased
3. So that I can load get data displayed without it taking a very long time

## Acceptance criteria
* Database performance increased
* Create indices based on bounding box per dataset

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Corgam** [comment]
No longer necessary due to performance being good.
