### ISSUE TITLE
Limiting the .yaml files for development deployments

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#317]
## Description
Implement a system to load different .yaml configuration files based on the current environment setting, optimizing configurations for development, testing, and production environments.

## Acceptance criteria
* .yaml files are correctly identified and loaded based on the current environment (test, production).
* System automatically adjusts configuration settings without manual intervention.
* Documentation exists on how configurations differ across environments and how to manage them.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into the`sprint-release` branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner-approved features
* All tests are passing
* Developers agreed to release

**Comment by Corgam** [comment]
Done during the last sprints. Moved to the "Done" column during the sprint meeting by POs. Closing.
