### ISSUE TITLE
Discussion needed - Implement area calculation for dataset 'House Footprints'

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#323]
## Description
Implement functionality to calculate the area covered by individual properties using the 'House Footprints' dataset. This feature is essential for urban planning, zoning purposes, and property tax calculations.

## User story
1. As a sustainability expert or real estate developer,
2. I want to calculate the area covered by buildings using accurate footprint data,
3. So that I can plan energy-efficient developments and assess environmental impacts accurately.

## Acceptance criteria
* Accurate area calculations based on the house footprints data.
* Provides reliable data that can be used for environmental impact assessments and resource management.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by dancingsushii** [comment]
Should be decided with PO's and SD in a separate meeting.

**Comment by Lucas-Nan** [comment]
well its already decided. Areas must be calculated in m2
