### ISSUE TITLE
Calculate distance to nearest EV charging station

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#324]
## Description
Develop a functionality that calculates the distance from a given location to the nearest electric vehicle charging station using the 'Charging Stations' dataset. This tool will help users plan routes and manage charging needs effectively. 

## Depends on 
#279 (Markers are interactive; clicking on a marker displays detailed information about the location or dataset)

## User story
1. As a sustainability expert or urban planner,
2. I want to be able to determine the distance to the nearest EV charging station from any given point,
3. So that I can evaluate and improve the accessibility of EV infrastructure as part of sustainable urban development plans.

## Acceptance criteria
* Users can enter a location and quickly find the nearest EV charging station.
* The system provides accurate and reliable distance measurements.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Corgam** [comment]
Done in #345
