### ISSUE TITLE
Implement geometric operations for dataset analysis

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#325]
## Description
Implement essential geometric operations on the dataset to enhance analytical capabilities. This includes calculating area and distance, as well as identifying the 'x' closest points of interest relative to a specific location. These operations are crucial for providing dynamic insights based on spatial data, and enhancing user interaction and data utility.

## Acceptance criteria
* #323
* #324

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Corgam** [comment]
Done in current sprint.
