### ISSUE TITLE
Develop getLocationData API Endpoint

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#332]
## Description
Develop the getLocationData API endpoint that retrieves data specific to a location selected on the frontend map. This endpoint will interface with the API Composer to fetch and aggregate data from all available datasets within the spatial database, providing comprehensive location-based insights.

## Acceptance criteria
* The `getLocationData` endpoint successfully accepts coordinates or an area as input.
* Data from multiple datasets is accurately queried and aggregated based on the location specified.
* The endpoint returns data in a structured format that is easy to interpret on the frontend.
* Ensure the response time is optimized for quick user interactions.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Corgam** [comment]
Done during the last sprints. Moved to the "Done" column during the sprint meeting by POs. Closing.
