### ISSUE TITLE
FE displaying metadata for map in second tab

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#333]
**Describe the bug**
Currently, only the metadata for the active map tab is fetched, thus not displaying metadata about ohter pinned but not selected maps

**To Reproduce**
1. Pin second map 
2.  Select metadata via tab menu
3. Metadata not fetching correctly

**Expected behavior**
Metadata should be displaying correctly, even for not active (but pinned) maps

**Screenshots**

![Image](https://github.com/amosproj/amos2024ss04-building-information-enhancer/assets/115190775/6a4e5c1b-ec2a-4546-8462-77536fc3f274)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Corgam** [comment]
Done with #347
