### ISSUE TITLE
Fix 'Actual Use' query

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#341]
**Describe the bug**
The 'Actual Use' query is currently based on outdated logic or has not been correctly integrated into the system. This issue leads to the query not functioning as intended or possibly retrieving incorrect data.

**To Reproduce**
1. Execute the 'Actual Use' query through the API or database interface.
2. Note any errors or unusual behaviors indicating the query's failure to retrieve expected results.

**Expected behavior**
The 'Actual Use' query should efficiently retrieve correct data without any errors, reflecting the latest updates and integration efforts.

**Comment by Lucas-Nan** [comment]
wrong ticket. either redundant or ambigous content. House footrpints are already included. actual use is not as far as i know

**Comment by Lucas-Nan** [comment]
fixed/added by @Superschnizel during refactoring
