### ISSUE TITLE
Calculation of building volume for each dataset

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#356]
## Description
Develop functionality to calculate the volume of buildings for each dataset. This calculation should utilize the dimensions extracted from the cityGML data.

## Acceptance criteria
* Implement a method to calculate building volume using the dimensions provided in the datasets.
* Volume calculations should be accurate and reflect the true dimensions of the buildings.
* Integration of this functionality into the existing data processing pipeline.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into the `sprint-release` branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner-approved features
* All tests are passing
* Developers agreed to release

**Comment by Lucas-Nan** [comment]
discussion result: do it with using ground height and distance to lowest roof start
