### ISSUE TITLE
Add missing info about citygml dataset

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#381]
**Describe the bug**
The CityGML data is correctly inserted in the db but some things to be able to see it and use it are still missing:
- no index is created (so also no bbox )
- no citygml handler for viewport (may be the same as the shape one but must be checked/added

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Lucas-Nan** [comment]
bug is fixed. was wrong type. instead of geometry it was geography

**Comment by Lucas-Nan** [comment]
another bug: missing type in metadatadb for fe handling
