### ISSUE TITLE
Finish Documentation

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#382]
## Description
Finish documentation:
PO:
- [x] planning document

SD:
- [x] README (Emil)
- [x] Github Wiki #85 
  - [x] API Composer
  - [x] API Gateway (Emil)
  - [x] Metadata Database (Emil & Leon)
  - [x] Frontend (Emil)
  - [x] SQL DB
  - [x] Data pipeline
- [x] User documentation (Lucas)
  - [x] Upload go Github 
- [x] design documentation (Emil)
  - [x] Upload go Github 
- [x] build documentation (Emil)
  - [x] Upload go Github 
- [x] Software bill of materials and upload from google drive to github(Tanja)

## User story
1. As a {}
2. I want / need {}
3. So that {}

## Acceptance criteria
* Criterion 1
* Criterion 2
* ...

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Lucas-Nan** [comment]
user doc so far. ofc open to changes

[User.pdf](https://github.com/user-attachments/files/16230957/User.pdf)

**Comment by Corgam** [comment]
Nice work @Lucas-Nan, but there are some functionalities missing. From the top of my head: tab info, 3D view, overall description of the data panel and its sections, adding a new dataset, hiding data view, reload data button, search favourites

**Comment by Lucas-Nan** [comment]
here with some extra stuff. with docx so further changes can be done directly

[User.docx](https://github.com/user-attachments/files/16236570/User.docx)


[User.pdf](https://github.com/user-attachments/files/16236579/User.pdf)

**Comment by Lucas-Nan** [comment]
with docx so changes can be directly

[User.docx](https://github.com/user-attachments/files/16236597/User.docx)
[User.pdf](https://github.com/user-attachments/files/16236596/User.pdf)
