### ISSUE TITLE
Calculation of building metrics via 3d data

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#386]
## Description
Calculate different metrics with the gross floor space for all different energy classes:
- Energy consumption
- CO2 emissions

## User story
1. As a User
2. I want information about energy consumption and CO2 emissions
3. So that I can access the information

## Acceptance criteria
* Criterion 1
* Criterion 2
* ...

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by nicolasbandel** [comment]
I did not find any formulars foor the energy classes. 
I have added:
 - the solar potential
 - the wall area per building
