### ISSUE TITLE
Create multimap view component

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#60]
## User story
1. As a frontend developer,
2. I want to implement a Multimap container and a TabController,
3. So that users can seamlessly switch between different map types and maintain state across map interactions.

## Acceptance criteria
* Integration with material UI needs to be checked (tab view needs to be implemented whether nicely with material UI or require a complete implementation).
* The Multimap container must synchronize zoom and location across multiple map instances.
* The TabController should allow users to switch between map, data, and 3D views without losing state.
* Implement smooth transitions and animations for switching tabs.
# Functionality Enhancements:
**Select Location via Searchbar:** Users must be able to enter a location in a search bar and have the map zoom into and center on that location.
**Select Location via Mouse Click:** Users must be able to click on any point on the map to select that location. The map should highlight the selected location visually.
**Toggle Legend:** Users should have the ability to toggle the visibility of the map legend with a button or switch.
**Adjust Map Settings via Button:** Provide a user interface control (button or similar) that allows users to adjust various map settings like zoom level, layers displayed, and other relevant parameters.

## Definition of done (DoD)
* Multimap and TabController components are fully functional.
* Integration with the main app has been tested.
* Code has been peer-reviewed.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by dancingsushii** [comment]
To do: define how the basic map view will look like.
