### ISSUE TITLE
Transfer all meeting notes and other relevant documentation to GitHub

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#76]
## Task specs
Transfer all existing meeting notes and relevant project documentation into a single, accessible location on GitHub.

## Deadline
15.05.2024

## Notes
* Ensure all team members are informed of the new documentation repository location and how to access it.

**Comment by Corgam** [comment]
Maybe it would be nice to store each meeting as a new file in the `Documentation` folder in the root of the repo? (The folder is already created)

**Comment by dancingsushii** [comment]
Whatever suits you better. I've moved some of our meeting notes to Wiki already (and I think it looks awkward tbh), but I can easily change this. This serves mainly for your convenience, so what is more useful for you: Wiki or the folder in the repo?

**Comment by dancingsushii** [comment]
All meeting notes and other documentation are stored in the custom sidebar of the [wiki](https://github.com/amosproj/amos2024ss04-building-information-enhancer/wiki). 
<img width="329" alt="image" src="https://github.com/amosproj/amos2024ss04-building-information-enhancer/assets/46463790/c5ae8377-2cb9-4267-8eb1-74b191d400e3">
