### ISSUE TITLE
Reimplemented and polish the 3D view component

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#78]
## User story
1. As a user,
2. I want a 3D view of the map that includes markers and overlays,
3. So that I can navigate and interact with spatial data in a more immersive environment.

## Acceptance criteria
* Implement a 3D map view with basic navigation tools (zoom, pan). 
* Markers and overlays are accurately represented in 3D space.
* Ensure performance and compatibility across supported devices.

## Definition of done (DoD)
* 3D view is fully functional and integrates with existing map functionalities.
* The feature is documented and merged into the mainline.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Corgam** [comment]
Renamed due to already finishing this task, deleting it, but finally the need to revert it and fix it into a working state.
