### ISSUE TITLE
Create generic pop-up container

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#79]
## User story
1. As a user,
2. I need a modal pop-up container that can be dismissed by clicking outside it,
3. So that I can focus on additional content without leaving the current page.

## Acceptance criteria
* The pop-up container appears with a close button and can also be closed by clicking on the greyed area around it.
* The container is responsive and accessible, working seamlessly across different screen dimensions.

## Definition of done (DoD)
* The pop-up container is implemented with clear, user-friendly interactions.
* It has been tested for accessibility and responsiveness.
* Code is reviewed, merged, and functioning as expected in the production environment.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Lucas-Nan** [comment]
well "generic pop up" is already kind of solved by material ui with "Dialog" which can be used with nearly no configuration
